# Evaluating NFL Win-Loss Potential Using KMeans Clustering Analysis

The purpose of this ananlysis is to use clustering analysis to identifying playing style archetypes within the NFL and compare the level of success between these archetypes measured by the number of wins obtained in a season over the span of a decade. The information resulting from this analysis may help identify team statistical attributes associated with success which could be useful for the purposes of sports betting or team building.

#### Imported Libraries

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold, train_test_split,GridSearchCV
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import completeness_score, homogeneity_score

#### Data

This data contains offensive and defensive seasonal statistics from every NFL team from the years 2010-2019 and is sourced from pro-football-reference.com. The dataset contains 320 observations and 53 features.

In [20]:
#Importing the dataset
nflData= pd.read_csv('data\\NFL_Combined.csv')
nflData.rename(columns= {'Unnamed: 0': 'Year'}, inplace= True)
nflData

,Year,Rk,Tm,ID,PF_Off,Yds_Off,Ply_Off,Y/P_Off,TO_Off,FL_Off,...,YdsRush_Def,TDrush_Def,Y/Arush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def,W
0,2010,27,Arizona Cardinals,1,289,4309,931,4.6,35,16,...,2323,19,4.4,123,108,894,38,39.7,13.2,5
1,2011,24,Arizona Cardinals,2,312,5192,993,5.2,32,9,...,1986,15,4.2,118,122,950,41,32.8,9.3,8
2,2012,31,Arizona Cardinals,3,250,4209,1018,4.1,34,13,...,2192,12,4.3,107,100,810,21,27.0,14.2,5
3,2013,16,Arizona Cardinals,4,379,5542,1037,5.3,31,9,...,1351,5,3.7,68,111,960,33,28.9,13.7,10
4,2014,24,Arizona Cardinals,5,310,5116,993,5.2,17,5,...,1739,9,4.4,77,130,1192,28,29.8,12.8,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,2015,10,Washington Redskins,316,388,5661,1011,5.6,22,11,...,1962,10,4.8,103,112,955,24,35.4,14.9,9
316,2016,12,Washington Redskins,317,396,6454,1009,6.4,21,9,...,1916,19,4.5,109,100,1023,34,38.5,11.8,8
317,2017,16,Washington Redskins,318,342,5199,982,5.3,27,14,...,2146,13,4.5,105,100,887,31,35.9,11.8,7
318,2018,29,Washington Redskins,319,281,4795,967,5.0,19,4,...,1860,12,4.5,109,102,791,24,35.1,14.6,7
319,2019,32,Washington Redskins,320,266,4395,885,5.0,21,8,...,2339,14,4.7,120,94,805,34,41.9,12.2,3

In [21]:
nflData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 53 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          320 non-null    int64
 1   Rk            320 non-null    int64
 2   Tm            320 non-null    object
 3   ID            320 non-null    int64
 4   PF_Off        320 non-null    int64
 5   Yds_Off       320 non-null    int64
 6   Ply_Off       320 non-null    int64
 7   Y/P_Off       320 non-null    float64
 8   TO_Off        320 non-null    int64
 9   FL_Off        320 non-null    int64
 10  1stDTot_Off   320 non-null    int64
 11  Cmp_Off       320 non-null    int64
 12  AttPass_Off   320 non-null    int64
 13  YdsPass_Off   320 non-null    int64
 14  TDPass_Off    320 non-null    int64
 15  Int_Off       320 non-null    int64
 16  NY/Apass_Off  320 non-null    float64
 17  1stDPass_Off  320 non-null    int64
 18  AttRush_Off   320 non-null    int64
 19  YdsRush_Off   320 non-null    int64
 20  TDrush_Off    320 non-null    int64
 21  Y/Arush_Off   320 non-null    float64
 22  1stDRush_Off  320 non-null    int64
 23  Pen_Off       320 non-null    int64
 24  PenYds_Off    320 non-null    int64
 25  1stPy_Off     320 non-null    int64
 26  Sc%_Off       320 non-null    float64
 27  TO%_Off       320 non-null    float64
 28  PF_Def        320 non-null    int64
 29  Yds_Def       320 non-null    int64
 30  Ply_Def       320 non-null    int64
 31  Y/P_Def       320 non-null    float64
 32  TO_Def        320 non-null    int64
 33  FL_Def        320 non-null    int64
 34  1stDTot_Def   320 non-null    int64
 35  Cmp_Def       320 non-null    int64
 36  AttPass_Def   320 non-null    int64
 37  YdsPass_Def   320 non-null    int64
 38  TDPass_Def    320 non-null    int64
 39  Int_Def       320 non-null    int64
 40  NY/Apass_Def  320 non-null    float64
 41  1stDPass_Def  320 non-null    int64
 42  AttRush_Def   320 non-null    int64
 43  YdsRush_Def   320 non-null    int64
 44  TDrush_Def    320 non-null    int64
 45  Y/Arush_Def   320 non-null    float64
 46  1stDrush_Def  320 non-null    int64
 47  Pen_Def       320 non-null    int64
 48  PenYds_Def    320 non-null    int64
 49  1stPy_Def     320 non-null    int64
 50  Sc%_Def       320 non-null    float64
 51  TO%_Def       320 non-null    float64
 52  W             320 non-null    int64
dtypes: float64(10), int64(42), object(1)
memory usage: 132.6+ KB

In [22]:
nflData.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,320.0,2014.500000,2.876780,2010.0,2012.000,2014.50,2017.000,2019.0
Rk,320.0,16.500000,9.247553,1.0,8.750,16.50,24.250,32.0
ID,320.0,160.500000,92.520268,1.0,80.750,160.50,240.250,320.0
PF_Off,320.0,362.290625,70.133012,193.0,311.500,361.00,406.000,606.0
Yds_Off,320.0,5542.271875,591.598582,3865.0,5108.000,5526.50,5956.250,7474.0
Ply_Off,320.0,1021.050000,47.915521,878.0,993.000,1017.50,1052.250,1191.0
Y/P_Off,320.0,5.422500,0.481045,4.1,5.100,5.40,5.800,6.8
TO_Off,320.0,23.743750,6.537327,8.0,19.000,23.00,28.000,44.0
FL_Off,320.0,9.534375,3.299863,2.0,7.000,9.00,11.000,22.0
1stDTot_Off,320.0,317.546875,36.029825,225.0,292.000,315.50,341.000,444.0
Cmp_Off,320.0,346.225000,46.697378,217.0,309.750,347.50,376.000,472.0
AttPass_Off,320.0,556.521875,59.321499,405.0,511.750,558.50,597.250,740.0
YdsPass_Off,320.0,3739.787500,586.489630,2179.0,3287.000,3738.00,4110.000,5444.0
TDPass_Off,320.0,24.615625,7.509601,8.0,20.000,24.00,29.000,55.0
Int_Off,320.0,14.209375,4.938802,2.0,11.000,14.00,17.250,30.0
NY/Apass_Off,320.0,6.290625,0.732779,4.2,5.700,6.20,6.800,8.3
1stDPass_Off,320.0,192.337500,30.114700,122.0,169.750,191.00,210.250,293.0
AttRush_Off,320.0,426.868750,49.430185,320.0,393.000,420.50,458.250,596.0
YdsRush_Off,320.0,1802.484375,327.677358,1156.0,1568.250,1758.00,1993.000,3296.0
TDrush_Off,320.0,12.700000,4.640425,3.0,9.000,12.00,16.000,29.0
Y/Arush_Off,320.0,4.206562,0.437635,3.1,3.900,4.20,4.500,5.5
1stDRush_Off,320.0,95.471875,19.515266,56.0,81.000,93.50,108.000,188.0
Pen_Off,320.0,104.465625,15.453401,55.0,94.000,104.00,113.000,163.0
PenYds_Off,320.0,889.515625,139.324478,415.0,800.750,885.00,967.000,1358.0
1stPy_Off,320.0,29.737500,7.178850,12.0,24.000,30.00,35.000,50.0
Sc%_Off,320.0,34.438437,6.504635,18.9,29.900,34.45,38.550,52.6
TO%_Off,320.0,12.085937,3.211415,4.1,9.800,11.70,14.500,21.0
PF_Def,320.0,362.290625,57.067687,225.0,319.750,359.50,400.250,494.0
Yds_Def,320.0,5542.268750,491.263999,4274.0,5234.250,5547.50,5885.500,7042.0
Ply_Def,320.0,1021.062500,43.895671,921.0,991.000,1017.00,1049.000,1150.0
Y/P_Def,320.0,5.428125,0.410393,4.4,5.100,5.40,5.700,6.6
TO_Def,320.0,23.743750,6.168732,7.0,19.000,23.50,28.000,44.0
FL_Def,320.0,9.534375,3.335767,2.0,7.000,10.00,12.000,23.0
1stDTot_Def,320.0,317.546875,27.733240,247.0,299.750,317.00,335.000,419.0
Cmp_Def,320.0,346.225000,32.256311,249.0,324.750,347.00,368.000,425.0
AttPass_Def,320.0,556.531250,40.925028,454.0,530.000,551.00,585.000,670.0
YdsPass_Def,320.0,3739.800000,392.579921,2707.0,3496.500,3752.00,3987.750,4796.0
TDPass_Def,320.0,24.615625,5.531251,11.0,21.000,24.00,29.000,45.0
Int_Def,320.0,14.209375,4.539956,2.0,11.000,14.00,17.000,31.0
NY/Apass_Def,320.0,6.303438,0.595611,4.8,5.900,6.30,6.700,7.9
1stDPass_Def,320.0,192.337500,19.979421,143.0,179.750,191.00,203.250,247.0
AttRush_Def,320.0,426.871875,43.218471,332.0,397.000,425.50,452.000,571.0
YdsRush_Def,320.0,1802.468750,280.767721,1004.0,1610.500,1797.00,1973.500,2714.0
TDrush_Def,320.0,12.700000,4.414709,3.0,10.000,12.00,15.000,31.0
Y/Arush_Def,320.0,4.214375,0.413995,3.0,3.900,4.20,4.500,5.3
1stDrush_Def,320.0,95.471875,16.600388,53.0,85.000,95.00,105.000,147.0
Pen_Def,320.0,104.468750,12.562282,69.0,96.750,104.50,113.000,144.0
PenYds_Def,320.0,889.553125,121.206126,613.0,805.000,885.50,971.000,1208.0
1stPy_Def,320.0,29.737500,7.522995,10.0,25.000,30.00,34.000,58.0
Sc%_Def,320.0,34.370000,4.839801,19.4,31.175,34.20,38.025,46.3
TO%_Def,320.0,12.108438,3.029286,3.9,9.900,12.20,14.100,21.0
W,320.0,7.975000,3.076761,0.0,6.000,8.00,10.000,15.0

In [23]:
#Discretizing the target column for better interpretability
#Four Categories: Losing-Low(0-4), Losing(5-8), Winning(9-12), Winning-High(13-16)
nflData['W_binned']= pd.cut(nflData['W'], bins=[0,4,8,12,16],labels=['Losing-Low','Losing','Winning','Winning-High'],include_lowest=True)
nflData

,Year,Rk,Tm,ID,PF_Off,Yds_Off,Ply_Off,Y/P_Off,TO_Off,FL_Off,...,TDrush_Def,Y/Arush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def,W,W_binned
0,2010,27,Arizona Cardinals,1,289,4309,931,4.6,35,16,...,19,4.4,123,108,894,38,39.7,13.2,5,Losing
1,2011,24,Arizona Cardinals,2,312,5192,993,5.2,32,9,...,15,4.2,118,122,950,41,32.8,9.3,8,Losing
2,2012,31,Arizona Cardinals,3,250,4209,1018,4.1,34,13,...,12,4.3,107,100,810,21,27.0,14.2,5,Losing
3,2013,16,Arizona Cardinals,4,379,5542,1037,5.3,31,9,...,5,3.7,68,111,960,33,28.9,13.7,10,Winning
4,2014,24,Arizona Cardinals,5,310,5116,993,5.2,17,5,...,9,4.4,77,130,1192,28,29.8,12.8,11,Winning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,2015,10,Washington Redskins,316,388,5661,1011,5.6,22,11,...,10,4.8,103,112,955,24,35.4,14.9,9,Winning
316,2016,12,Washington Redskins,317,396,6454,1009,6.4,21,9,...,19,4.5,109,100,1023,34,38.5,11.8,8,Losing
317,2017,16,Washington Redskins,318,342,5199,982,5.3,27,14,...,13,4.5,105,100,887,31,35.9,11.8,7,Losing
318,2018,29,Washington Redskins,319,281,4795,967,5.0,19,4,...,12,4.5,109,102,791,24,35.1,14.6,7,Losing
319,2019,32,Washington Redskins,320,266,4395,885,5.0,21,8,...,14,4.7,120,94,805,34,41.9,12.2,3,Losing-Low

#### Preparing Data for KMeans Clustering

In [24]:
#Separating out numerical statistical values
statsMatrix= nflData.loc[:,'PF_Off':'TO%_Def']
statsMatrix

,PF_Off,Yds_Off,Ply_Off,Y/P_Off,TO_Off,FL_Off,1stDTot_Off,Cmp_Off,AttPass_Off,YdsPass_Off,...,AttRush_Def,YdsRush_Def,TDrush_Def,Y/Arush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def
0,289,4309,931,4.6,35,16,241,285,561,2921,...,526,2323,19,4.4,123,108,894,38,39.7,13.2
1,312,5192,993,5.2,32,9,286,307,550,3567,...,475,1986,15,4.2,118,122,950,41,32.8,9.3
2,250,4209,1018,4.1,34,13,246,337,608,3005,...,506,2192,12,4.3,107,100,810,21,27.0,14.2
3,379,5542,1037,5.3,31,9,329,363,574,4002,...,370,1351,5,3.7,68,111,960,33,28.9,13.7
4,310,5116,993,5.2,17,5,302,320,568,3808,...,396,1739,9,4.4,77,130,1192,28,29.8,12.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,388,5661,1011,5.6,22,11,317,386,555,4095,...,406,1962,10,4.8,103,112,955,24,35.4,14.9
316,396,6454,1009,6.4,21,9,345,407,607,4758,...,423,1916,19,4.5,109,100,1023,34,38.5,11.8
317,342,5199,982,5.3,27,14,278,347,540,3751,...,472,2146,13,4.5,105,100,887,31,35.9,11.8
318,281,4795,967,5.0,19,4,280,311,509,3021,...,413,1860,12,4.5,109,102,791,24,35.1,14.6
319,266,4395,885,5.0,21,8,248,298,479,2812,...,493,2339,14,4.7,120,94,805,34,41.9,12.2

There are several feateures such as total yards on offense (Yds_Off) that are redundant or used to create other stats. These features must be removed to avoid biasing the analysis. In the case of redundant features, more granular feature were preferred as they are more descriptive. For example, total passing yards and total rushing yards are preferrable to total yards.

In [25]:
#Removing some redundant features
statsMatrix.drop(columns=['Yds_Off','Ply_Off','Y/P_Off','TO_Off','1stDTot_Off','NY/Apass_Off','Y/Arush_Off','Yds_Def','Ply_Def','Y/P_Def','TO_Def','1stDTot_Def','NY/Apass_Def','Y/Arush_Def'],inplace=True)
statsMatrix

,PF_Off,FL_Off,Cmp_Off,AttPass_Off,YdsPass_Off,TDPass_Off,Int_Off,1stDPass_Off,AttRush_Off,YdsRush_Off,...,1stDPass_Def,AttRush_Def,YdsRush_Def,TDrush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def
0,289,16,285,561,2921,10,19,154,320,1388,...,178,526,2323,19,123,108,894,38,39.7,13.2
1,312,9,307,550,3567,21,23,175,389,1625,...,174,475,1986,15,118,122,950,41,32.8,9.3
2,250,13,337,608,3005,11,21,168,352,1204,...,160,506,2192,12,107,100,810,21,27.0,14.2
3,379,9,363,574,4002,24,22,205,422,1540,...,208,370,1351,5,68,111,960,33,28.9,13.7
4,310,5,320,568,3808,21,12,191,397,1308,...,195,396,1739,9,77,130,1192,28,29.8,12.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,388,11,386,555,4095,30,11,208,429,1566,...,202,406,1962,10,103,112,955,24,35.4,14.9
316,396,9,407,607,4758,25,12,226,379,1696,...,225,423,1916,19,109,100,1023,34,38.5,11.8
317,342,14,347,540,3751,27,13,191,401,1448,...,171,472,2146,13,105,100,887,31,35.9,11.8
318,281,4,311,509,3021,16,15,156,414,1774,...,197,413,1860,12,109,102,791,24,35.1,14.6
319,266,8,298,479,2812,18,13,154,356,1583,...,200,493,2339,14,120,94,805,34,41.9,12.2

The scales of the remaining features vary significantly. As a result, some features may have more influence determining the similarity between teams despite being equal in importance to other statistics. To mitigate this issue, min-max normalization is applied to the features of the statistical matrix.

In [26]:
#Standardizing the feature values using Min-Max Normaliztion
MnMx= MinMaxScaler()
statsMatrixSc= MnMx.fit_transform(statsMatrix)
statsMatrixSc

array([[0.23244552, 0.7       , 0.26666667, ..., 0.58333333, 0.75464684,
        0.54385965],
       [0.28813559, 0.35      , 0.35294118, ..., 0.64583333, 0.49814126,
        0.31578947],
       [0.13801453, 0.55      , 0.47058824, ..., 0.22916667, 0.28252788,
        0.60233918],
       ...,
       [0.36077482, 0.6       , 0.50980392, ..., 0.4375    , 0.6133829 ,
        0.4619883 ],
       [0.21307506, 0.1       , 0.36862745, ..., 0.29166667, 0.58364312,
        0.62573099],
       [0.17675545, 0.3       , 0.31764706, ..., 0.5       , 0.83643123,
        0.48538012]])

The initial pass of KMeans will use k value of 4. This value was chosen because number of wins feature was binned into 4 classes. The purity of the resulting clusters in regard to the classes of winning will be evaluated using homogeneity and completeness scores. The resulting cluster means will be evaluated to identify the features that are most characteristic of the teams within the cluster.

In [27]:
#Reporting the 4 cluster centers
km4= KMeans(n_clusters=4, random_state=9)
km4.fit(statsMatrixSc)
km4.cluster_centers_

array([[0.26815981, 0.46      , 0.46960784, 0.46858209, 0.41155436,
        0.26968085, 0.55133929, 0.34429825, 0.26263587, 0.23595794,
        0.27403846, 0.22443182, 0.47835648, 0.52319724, 0.41611842,
        0.30348665, 0.61982249, 0.72016729, 0.27440476, 0.51384943,
        0.36828704, 0.51859742, 0.48455882, 0.33362069, 0.48137019,
        0.57186192, 0.60025585, 0.45982143, 0.5875    , 0.4585    ,
        0.44487395, 0.42838542, 0.71570632, 0.34758772],
       [0.54713479, 0.34055556, 0.68204793, 0.59512438, 0.67326187,
        0.49692671, 0.41706349, 0.60220923, 0.32805958, 0.2621028 ,
        0.40811966, 0.28846801, 0.45226337, 0.49248262, 0.53654971,
        0.61519947, 0.44135437, 0.56869062, 0.37407407, 0.65511364,
        0.56563786, 0.62448274, 0.46666667, 0.42681992, 0.59893162,
        0.33417015, 0.45618583, 0.36230159, 0.46217494, 0.51896296,
        0.51232493, 0.41041667, 0.61664601, 0.50565302],
       [0.51346852, 0.33046875, 0.40012255, 0.29412313, 0.40863323,
        0.36901596, 0.29241071, 0.33707968, 0.59567482, 0.47114486,
        0.52524038, 0.46034564, 0.4369213 , 0.48916357, 0.44449013,
        0.57228301, 0.32701553, 0.31714684, 0.42931548, 0.60182884,
        0.58897569, 0.46239229, 0.33731618, 0.51616379, 0.47265625,
        0.23077929, 0.3311769 , 0.22712054, 0.30651596, 0.42270833,
        0.40477941, 0.40722656, 0.41542751, 0.61138523],
       [0.32107664, 0.37151163, 0.4372549 , 0.40541479, 0.38722177,
        0.26991588, 0.45556478, 0.32918537, 0.40984159, 0.27966746,
        0.31529517, 0.25942565, 0.46080965, 0.5062517 , 0.45746634,
        0.3636395 , 0.47646897, 0.39798565, 0.36877076, 0.4440407 ,
        0.39341085, 0.35957452, 0.2999316 , 0.42542101, 0.3388864 ,
        0.42361584, 0.45521556, 0.31312292, 0.42293419, 0.47550388,
        0.47824897, 0.39898256, 0.45046252, 0.47864817]])

In [28]:
#Viewing the distribution of teams within the 4 clusters
cluster_assignments= km4.predict(statsMatrixSc)
pd.Series(cluster_assignments).value_counts()

1    90
3    86
0    80
2    64
dtype: int64

#### Evaluating Cluster Purity

The resulting clusters are evaluated for purity using homogeity and completeness scores relative to the 4 winning classes developed above. Scores closer to 1.0 indicate that the clusters are homogenous and therefore closely associated with number of wins in a season.

In [29]:
homogeneity_score(nflData['W_binned'],cluster_assignments)

0.2540751887696435

In [30]:
completeness_score(nflData['W_binned'],cluster_assignments)

0.22340135622607654

#### Evaluating Cluster Means

In [31]:
k4centers= pd.DataFrame(km4.cluster_centers_,columns=statsMatrix.columns)
k4centers

,PF_Off,FL_Off,Cmp_Off,AttPass_Off,YdsPass_Off,TDPass_Off,Int_Off,1stDPass_Off,AttRush_Off,YdsRush_Off,...,1stDPass_Def,AttRush_Def,YdsRush_Def,TDrush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def
0,0.268160,0.460000,0.469608,0.468582,0.411554,0.269681,0.551339,0.344298,0.262636,0.235958,...,0.481370,0.571862,0.600256,0.459821,0.587500,0.458500,0.444874,0.428385,0.715706,0.347588
1,0.547135,0.340556,0.682048,0.595124,0.673262,0.496927,0.417063,0.602209,0.328060,0.262103,...,0.598932,0.334170,0.456186,0.362302,0.462175,0.518963,0.512325,0.410417,0.616646,0.505653
2,0.513469,0.330469,0.400123,0.294123,0.408633,0.369016,0.292411,0.337080,0.595675,0.471145,...,0.472656,0.230779,0.331177,0.227121,0.306516,0.422708,0.404779,0.407227,0.415428,0.611385
3,0.321077,0.371512,0.437255,0.405415,0.387222,0.269916,0.455565,0.329185,0.409842,0.279667,...,0.338886,0.423616,0.455216,0.313123,0.422934,0.475504,0.478249,0.398983,0.450463,0.478648

For each cluster we will indentify features where its average value within the cluster is the highest among all clusters. These features will be used to characterize each cluster.

In [32]:
#Indentifying the cluster with the highest average value for each feature
featmax= k4centers.idxmax()
featmax

PF_Off          1
FL_Off          0
Cmp_Off         1
AttPass_Off     1
YdsPass_Off     1
TDPass_Off      1
Int_Off         0
1stDPass_Off    1
AttRush_Off     2
YdsRush_Off     2
TDrush_Off      2
1stDRush_Off    2
Pen_Off         0
PenYds_Off      0
1stPy_Off       1
Sc%_Off         1
TO%_Off         0
PF_Def          0
FL_Def          2
Cmp_Def         1
AttPass_Def     2
YdsPass_Def     1
TDPass_Def      0
Int_Def         2
1stDPass_Def    1
AttRush_Def     0
YdsRush_Def     0
TDrush_Def      0
1stDrush_Def    0
Pen_Def         1
PenYds_Def      1
1stPy_Def       0
Sc%_Def         0
TO%_Def         2
dtype: int64

In [33]:
clust= {}

for f in featmax.index:
    if featmax[f] in clust:
        clust[featmax[f]].append(f)
    else:
        clust[featmax[f]]= [f]

for c in clust:
    print('Cluster {}:'.format(c),clust[c],'\n')

Cluster 1: ['PF_Off', 'Cmp_Off', 'AttPass_Off', 'YdsPass_Off', 'TDPass_Off', '1stDPass_Off', '1stPy_Off', 'Sc%_Off', 'Cmp_Def', 'YdsPass_Def', '1stDPass_Def', 'Pen_Def', 'PenYds_Def']

Cluster 0: ['FL_Off', 'Int_Off', 'Pen_Off', 'PenYds_Off', 'TO%_Off', 'PF_Def', 'TDPass_Def', 'AttRush_Def', 'YdsRush_Def', 'TDrush_Def', '1stDrush_Def', '1stPy_Def', 'Sc%_Def']

Cluster 2: ['AttRush_Off', 'YdsRush_Off', 'TDrush_Off', '1stDRush_Off', 'FL_Def', 'AttPass_Def', 'Int_Def', 'TO%_Def']

#### Results

Defining the clusters:

cluster 0:
These teams are prone to turnovers and costly penalties on offense and are vulnerable to the run game on defense.

cluster 1:
These teams have high scoring, passing oriented offenses, but notably weak, undisciplined defense particularly against the pass.

cluster 2:
These teams have running oriented offenses and tend to have defenses that force turnovers.

cluster 3:
These teams are not particularly notable in any statistical category.

In [37]:
#Creating new dataframe with cluster assignments
k4complete= pd.DataFrame(statsMatrix,columns=statsMatrix.columns)
k4complete['Cluster']= pd.Series(cluster_assignments)
k4complete['Wins']= nflData['W']
k4complete['W_binned']= nflData['W_binned']
k4complete

,PF_Off,FL_Off,Cmp_Off,AttPass_Off,YdsPass_Off,TDPass_Off,Int_Off,1stDPass_Off,AttRush_Off,YdsRush_Off,...,TDrush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def,Cluster,Wins,W_binned
0,289,16,285,561,2921,10,19,154,320,1388,...,19,123,108,894,38,39.7,13.2,0,5,Losing
1,312,9,307,550,3567,21,23,175,389,1625,...,15,118,122,950,41,32.8,9.3,0,8,Losing
2,250,13,337,608,3005,11,21,168,352,1204,...,12,107,100,810,21,27.0,14.2,3,5,Losing
3,379,9,363,574,4002,24,22,205,422,1540,...,5,68,111,960,33,28.9,13.7,1,10,Winning
4,310,5,320,568,3808,21,12,191,397,1308,...,9,77,130,1192,28,29.8,12.8,3,11,Winning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,388,11,386,555,4095,30,11,208,429,1566,...,10,103,112,955,24,35.4,14.9,1,9,Winning
316,396,9,407,607,4758,25,12,226,379,1696,...,19,109,100,1023,34,38.5,11.8,1,8,Losing
317,342,14,347,540,3751,27,13,191,401,1448,...,13,105,100,887,31,35.9,11.8,0,7,Losing
318,281,4,311,509,3021,16,15,156,414,1774,...,12,109,102,791,24,35.1,14.6,3,7,Losing
319,266,8,298,479,2812,18,13,154,356,1583,...,14,120,94,805,34,41.9,12.2,0,3,Losing-Low

Distribution of Wins by Cluster

In [45]:
#Total number of teams within each cluster
k4complete['Cluster'].value_counts()

1    90
3    86
0    80
2    64
Name: Cluster, dtype: int64

In [47]:
#Distribution of win categories by cluster
#Losing-Low(0-4), Losing(5-8), Winning(9-12), Winning-High(13-16)
pd.crosstab(k4complete['Cluster'],k4complete['W_binned'], margins=True)

W_binned  Losing-Low  Losing  Winning  Winning-High  All
Cluster
0                 41      37        2             0   80
1                  3      40       37            10   90
2                  0       6       46            12   64
3                  4      49       31             2   86
All               48     132      116            24  320

In [49]:
#Distribution of win categories by cluster as a percentage of total cluster size
#Losing-Low(0-4), Losing(5-8), Winning(9-12), Winning-High(13-16)
pd.crosstab(k4complete['Cluster'],k4complete['W_binned'], normalize='index')

W_binned  Losing-Low    Losing   Winning  Winning-High
Cluster
0           0.512500  0.462500  0.025000      0.000000
1           0.033333  0.444444  0.411111      0.111111
2           0.000000  0.093750  0.718750      0.187500
3           0.046512  0.569767  0.360465      0.023256

In [39]:
#Distribution of total number of wins by cluster
pd.crosstab(k4complete['Cluster'],k4complete['Wins'])

Wins     0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
Cluster
0         1   1  10  11  18   9  14   7   7   0   1   1   0   0   0   0
1         0   0   0   1   2   7   8  15  10  11  10   6  10   9   0   1
2         0   0   0   0   0   0   0   4   2   6  15  14  11   8   3   1
3         0   0   0   0   4   8  11  16  14  13  10   5   3   2   0   0

Statistical Summary of Clusters

In [40]:
#Cluster 0: High Turnovers, Costly Penalties, poor run defense
k4_cluster0= k4complete[k4complete['Cluster']==0]
k4_cluster0.describe()

,PF_Off,FL_Off,Cmp_Off,AttPass_Off,YdsPass_Off,TDPass_Off,Int_Off,1stDPass_Off,AttRush_Off,YdsRush_Off,...,YdsRush_Def,TDrush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def,Cluster,Wins
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,...,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,80.000000
mean,303.750000,11.200000,336.750000,561.975000,3522.725000,20.675000,17.437500,180.875000,392.487500,1660.950000,...,2030.437500,15.875000,108.225000,103.387500,877.700000,30.562500,38.652500,9.843750,0.0,4.762500
std,46.419796,3.519925,38.360878,51.761374,449.511858,5.071077,4.327843,22.622591,38.170833,282.885892,...,266.079071,4.384596,15.629391,13.661823,124.717037,7.828613,3.110781,2.479171,0.0,2.118297
min,193.000000,4.000000,256.000000,455.000000,2289.000000,8.000000,8.000000,125.000000,320.000000,1156.000000,...,1566.000000,7.000000,77.000000,69.000000,634.000000,13.000000,31.000000,3.900000,0.0,0.000000
25%,276.750000,9.000000,306.250000,524.750000,3255.000000,17.000000,14.750000,161.750000,361.500000,1447.750000,...,1810.250000,13.000000,97.250000,94.750000,790.750000,25.000000,36.675000,8.175000,0.0,3.000000
50%,307.000000,11.000000,336.000000,557.500000,3560.500000,21.000000,18.000000,180.000000,386.500000,1632.000000,...,2011.000000,15.000000,105.500000,103.500000,890.500000,31.000000,38.900000,9.700000,0.0,4.000000
75%,337.250000,14.000000,365.000000,605.500000,3805.750000,24.000000,20.000000,197.250000,409.250000,1820.250000,...,2225.250000,18.000000,120.250000,112.250000,948.500000,35.250000,40.725000,11.825000,0.0,6.000000
max,445.000000,22.000000,445.000000,681.000000,4729.000000,32.000000,29.000000,237.000000,512.000000,2408.000000,...,2714.000000,31.000000,147.000000,144.000000,1208.000000,58.000000,46.300000,15.300000,0.0,11.000000

In [41]:
#Cluster 1: High Scoring Pass Offense, Undisciplined,Poor Defense against the pass
k4_cluster1= k4complete[k4complete['Cluster']==1]
k4_cluster1.describe()

,PF_Off,FL_Off,Cmp_Off,AttPass_Off,YdsPass_Off,TDPass_Off,Int_Off,1stDPass_Off,AttRush_Off,YdsRush_Off,...,YdsRush_Def,TDrush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def,Cluster,Wins
count,90.000000,90.000000,90.000000,90.000000,90.00000,90.000000,90.000000,90.000000,90.000000,90.00000,...,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.0,90.000000
mean,418.966667,8.811111,390.922222,604.366667,4377.20000,31.355556,13.677778,224.977778,410.544444,1716.90000,...,1784.077778,13.144444,96.444444,107.922222,917.833333,29.700000,35.987778,12.546667,1.0,8.844444
std,57.569391,3.165454,35.412887,43.179128,413.42152,7.042904,4.617572,22.892017,36.657590,225.81732,...,229.232830,3.664470,14.559534,11.596423,121.348162,7.691305,4.022488,2.593605,0.0,2.685421
min,320.000000,2.000000,306.000000,512.000000,3427.00000,18.000000,4.000000,173.000000,333.000000,1221.00000,...,1181.000000,5.000000,60.000000,79.000000,641.000000,10.000000,26.900000,8.200000,1.0,3.000000
25%,379.250000,7.000000,368.500000,574.000000,4090.50000,27.000000,11.000000,210.000000,389.250000,1527.25000,...,1626.000000,11.000000,88.000000,100.250000,843.250000,25.000000,33.125000,10.500000,1.0,7.000000
50%,410.000000,8.500000,384.500000,598.000000,4301.50000,30.000000,14.000000,222.000000,408.500000,1725.50000,...,1806.000000,13.000000,99.000000,109.000000,920.000000,30.000000,35.600000,12.650000,1.0,9.000000
75%,449.250000,11.000000,410.000000,631.500000,4661.75000,35.000000,17.000000,237.750000,435.750000,1872.75000,...,1939.250000,15.000000,104.000000,115.000000,987.250000,34.750000,39.275000,14.175000,1.0,11.000000
max,606.000000,16.000000,472.000000,740.000000,5444.00000,55.000000,30.000000,293.000000,523.000000,2231.00000,...,2361.000000,21.000000,130.000000,136.000000,1202.000000,54.000000,45.300000,20.400000,1.0,15.000000

In [42]:
#Cluster 2: Running Offense, Strong Defense 
k4_cluster2= k4complete[k4complete['Cluster']==2]
k4_cluster2.describe()

,PF_Off,FL_Off,Cmp_Off,AttPass_Off,YdsPass_Off,TDPass_Off,Int_Off,1stDPass_Off,AttRush_Off,YdsRush_Off,...,YdsRush_Def,TDrush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def,Cluster,Wins
count,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.00000,64.000000,64.000000,64.000000,64.0,64.000000
mean,405.062500,8.609375,319.031250,503.531250,3513.187500,25.343750,10.187500,179.640625,484.406250,2164.250000,...,1570.312500,9.359375,81.812500,100.703125,853.84375,29.546875,30.575000,14.354687,2.0,10.859375
std,44.667688,2.292965,34.035448,48.304579,385.538991,5.901893,3.531603,18.184563,36.420262,306.919099,...,220.954486,3.751686,13.260366,13.234970,113.87186,6.049871,4.161959,2.769558,0.0,1.807104
min,321.000000,4.000000,244.000000,405.000000,2751.000000,14.000000,2.000000,148.000000,396.000000,1422.000000,...,1004.000000,3.000000,53.000000,69.000000,613.00000,14.000000,19.400000,9.000000,2.0,7.000000
25%,374.250000,7.000000,291.750000,473.000000,3216.500000,21.000000,8.000000,164.750000,461.500000,1968.250000,...,1412.750000,7.000000,72.000000,90.750000,779.75000,25.000000,27.275000,11.975000,2.0,10.000000
50%,402.000000,9.000000,314.500000,501.000000,3539.500000,24.500000,9.000000,176.500000,481.000000,2119.000000,...,1552.000000,9.000000,81.500000,101.000000,858.00000,30.000000,30.150000,14.250000,2.0,11.000000
75%,428.500000,10.000000,344.250000,538.250000,3791.250000,29.000000,12.250000,196.250000,502.000000,2331.500000,...,1734.500000,11.000000,91.000000,110.250000,928.50000,33.000000,33.300000,16.150000,2.0,12.000000
max,531.000000,14.000000,386.000000,620.000000,4308.000000,38.000000,20.000000,210.000000,596.000000,3296.000000,...,2130.000000,22.000000,122.000000,137.000000,1191.00000,44.000000,39.300000,21.000000,2.0,15.000000

In [43]:
#Cluster 3: Average Offense and Defense
k4_cluster3= k4complete[k4complete['Cluster']==3]
k4_cluster3.describe()

,PF_Off,FL_Off,Cmp_Off,AttPass_Off,YdsPass_Off,TDPass_Off,Int_Off,1stDPass_Off,AttRush_Off,YdsRush_Off,...,YdsRush_Def,TDrush_Def,1stDrush_Def,Pen_Def,PenYds_Def,1stPy_Def,Sc%_Def,TO%_Def,Cluster,Wins
count,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,...,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.0,86.000000
mean,325.604651,9.430233,328.500000,540.813953,3443.279070,20.686047,14.755814,178.290698,433.116279,1754.488372,...,1782.418605,11.767442,92.755814,104.662791,897.558140,29.151163,31.517442,12.084884,3.0,7.906977
std,46.281563,3.337984,39.622557,47.110262,460.239341,5.590457,4.469336,23.692573,38.711427,279.096346,...,220.412846,3.435710,12.364024,11.122431,116.810818,8.084142,3.166152,2.677335,0.0,2.145463
min,212.000000,2.000000,217.000000,429.000000,2179.000000,11.000000,4.000000,122.000000,352.000000,1204.000000,...,1337.000000,4.000000,68.000000,79.000000,676.000000,11.000000,23.600000,5.500000,3.0,4.000000
25%,289.000000,7.000000,299.000000,504.250000,3103.500000,16.000000,12.000000,162.000000,409.000000,1591.500000,...,1632.750000,9.250000,84.250000,97.000000,806.250000,24.000000,29.400000,10.325000,3.0,6.000000
50%,325.000000,9.000000,329.500000,539.500000,3411.500000,20.000000,14.000000,179.000000,426.500000,1737.000000,...,1789.000000,11.000000,92.000000,104.000000,882.000000,29.000000,31.700000,12.300000,3.0,8.000000
75%,355.000000,11.000000,354.000000,577.750000,3760.000000,23.000000,17.500000,192.000000,456.750000,1902.500000,...,1919.000000,14.000000,99.750000,112.000000,983.250000,34.000000,33.600000,13.975000,3.0,9.000000
max,441.000000,18.000000,450.000000,661.000000,4519.000000,34.000000,26.000000,236.000000,546.000000,2632.000000,...,2359.000000,22.000000,126.000000,130.000000,1196.000000,50.000000,38.000000,19.000000,3.0,13.000000

#### Conclusion

After several runs of KMeans using a k-value of 4, a consistent set of cluster with distinct characteristics emerges. The teams evaluated in this dataset fall into one of 4 clusters:

High scoring, passing offense/Mistake-prone, poor pass defense
Running-oriented offense/Strong, turnover forcing defense
High turnover, mistake-prone offense/Poor run defense
Average offense and defense

Of these 4 archetypes, the most successful in terms of winning by a significant margin are Running-oriented offense/Strong, turnover forcing defense teams. Of the football teams within this cluster, 90.63% finished the season with winning records. By comparison, only 52.22% of teams in the second most successful group, High-scoring pass offense/Mistake-prone, poor pass defense experienced a winning season. Unsurprisingly the cluster defined by offensive turnovers, penalties, and poor run defense were the least successful. Only 2.5% of these teams were able to finish the season with a winning record. Average teams, largely unremarkable in any offensive or defensive category generally fair poorly. 61.63% of teams with average performance end the season with a losing record. This suggests that teams may be better off figuring out how to strategically specialize their teams and maximize their advantages rather than creating balanced teams that are decent at most things, but great at nothing.

Interestingly, despite clearly being the most successful, the running offense/strong defense cluster is notably smaller than the other groups. The NFL is sometimes referred to as a copy cat league, where teams often chase success by copying the successful. If this is true, one might expect a greater number of total teams and more balance between winning and losing teams in this group, but this is not the case. One possibility may be that despite teams of this archetype having more regular season success, they may not have as much playoff or Super Bowl success, which is the ultimate goal of all NFL teams. It is possible that teams with greater post-season success have different characteristics than those defining this group. In this case, teams may try to imitate those teams rather than those of the running offense/strong defense archetype. This could be evaluated in the future using data that includes playoff records and stats.